export const drinkNames =[
	{value: 1    , label: "'57 Chevy with a White License Plate"},
    {value: 2    , label: "1-900-FUK-MEUP"},
    {value: 3    , label: "110 in the Shade"},
    {value: 4    , label: "151 Florida Bushwacker"},
    {value: 5    , label: "155 Belmont"},
    {value: 6    , label: "24k Nightmare"},
    {value: 7    , label: "252"},
    {value: 8    , label: "3 Wise Men"},
    {value: 9    , label: "3-Mile Long Island Iced Tea"},
    {value: 10   , label: "410 Gone"},
    {value: 11   , label: "50/50"},
    {value: 12   , label: "501 Blue"},
    {value: 13   , label: "69 Special"},
    {value: 14   , label: "747"},
    {value: 15   , label: "9 1/2 Weeks"},
    {value: 16   , label: "A Day at the Beach"},
    {value: 17   , label: "A Furlong Too Late"},
    {value: 18   , label: "A Gilligan's Island"},
    {value: 19   , label: "A Night In Old Mandalay"},
    {value: 20   , label: "A Piece of Ass"},
    {value: 21   , label: "A Splash of Nash"},
    {value: 22   , label: "A True Amaretto Sour"},
    {value: 23   , label: "A midsummernight dream"},
    {value: 24   , label: "A. J."},
    {value: 25   , label: "A.D.M. (After Dinner Mint)"},
    {value: 26   , label: "A1"},
    {value: 27   , label: "ABC"},
    {value: 28   , label: "ACID"},
    {value: 29   , label: "AT&T"},
    {value: 30   , label: "Abbey Cocktail"},
    {value: 31   , label: "Abbey Martini"},
    {value: 32   , label: "Abilene"},
    {value: 33   , label: "Absinthe #2"},
    {value: 34   , label: "Absolut Evergreen"},
    {value: 35   , label: "Absolut Sex"},
    {value: 36   , label: "Absolut Stress #2"},
    {value: 37   , label: "Absolut Summertime"},
    {value: 38   , label: "Absolut limousine"},
    {value: 39   , label: "Absolutely Cranberry Smash"},
    {value: 40   , label: "Absolutely Fabulous"},
    {value: 41   , label: "Absolutly Screwed Up"},
    {value: 42   , label: "Acapulco"},
    {value: 43   , label: "Ace"},
    {value: 44   , label: "Adam"},
    {value: 45   , label: "Adam & Eve"},
    {value: 46   , label: "Adam Bomb"},
    {value: 47   , label: "Adam Sunrise"},
    {value: 48   , label: "Addington"},
    {value: 49   , label: "Addison"},
    {value: 50   , label: "Addison Special"},
    {value: 51   , label: "Adios Amigos Cocktail"},
    {value: 52   , label: "Adonis Cocktail"},
    {value: 53   , label: "Affair"},
    {value: 54   , label: "Affinity"},
    {value: 55   , label: "After Dinner Cocktail"},
    {value: 56   , label: "After Five"},
    {value: 57   , label: "After Supper Cocktail"},
    {value: 58   , label: "After sex"},
    {value: 59   , label: "Afterglow"},
    {value: 60   , label: "Afternoon"},
    {value: 61   , label: "Alabama Slammer"},
    {value: 62   , label: "Alaska Cocktail"},
    {value: 63   , label: "Alexander"},
    {value: 64   , label: "Alfie Cocktail"},
    {value: 65   , label: "Algonquin"},
    {value: 66   , label: "Alice Cocktail"},
    {value: 67   , label: "Alice in Wonderland"},
    {value: 68   , label: "Allegheny"},
    {value: 69   , label: "Allies Cocktail"},
    {value: 70   , label: "Almeria"},
    {value: 71   , label: "Almond Chocolate Coffee"},
    {value: 72   , label: "Almond Joy"},
    {value: 73   , label: "Aloha Fruit punch"},
    {value: 74   , label: "Amaretto And Cream"},
    {value: 75   , label: "Amaretto Liqueur"},
    {value: 76   , label: "Amaretto Mist"},
    {value: 77   , label: "Amaretto Rose"},
    {value: 78   , label: "Amaretto Shake"},
    {value: 79   , label: "Amaretto Sour"},
    {value: 80   , label: "Amaretto Stinger"},
    {value: 81   , label: "Amaretto Stone Sour"},
    {value: 82   , label: "Amaretto Stone Sour #3"},
    {value: 83   , label: "Amaretto Sunrise"},
    {value: 84   , label: "Amaretto Sunset"},
    {value: 85   , label: "Amaretto Sweet & Sour"},
    {value: 86   , label: "Amaretto Tea"},
    {value: 87   , label: "Americano"},
    {value: 88   , label: "Angel Face"},
    {value: 89   , label: "Angelica Liqueur"},
    {value: 90   , label: "Apello"},
    {value: 91   , label: "Apple Berry Smoothie"},
    {value: 92   , label: "Apple Cider Punch #1"},
    {value: 93   , label: "Apple Grande"},
    {value: 94   , label: "Apple Karate"},
    {value: 95   , label: "Apple Pie with A Crust"},
    {value: 96   , label: "Apple Slammer"},
    {value: 97   , label: "Applecar"},
    {value: 98   , label: "Applejack"},
    {value: 99   , label: "Apricot Lady"},
    {value: 100  , label: "Apricot Punch"},
    {value: 101  , label: "Archbishop"},
    {value: 102  , label: "Arctic Fish"},
    {value: 103  , label: "Arctic Mouthwash"},
    {value: 104  , label: "Arise My Love"},
    {value: 105  , label: "Arizona Antifreeze"},
    {value: 106  , label: "Arizona Stingers"},
    {value: 107  , label: "Arizona Twister"},
    {value: 108  , label: "Army Special"},
    {value: 109  , label: "Arthur Tompkins"},
    {value: 110  , label: "Artillery"},
    {value: 111  , label: "Artillery Punch"},
    {value: 112  , label: "Atlantic Sun"},
    {value: 113  , label: "Atomic Lokade"},
    {value: 114  , label: "Auburn Headbanger"},
    {value: 115  , label: "Autodafé"},
    {value: 116  , label: "Avalanche"},
    {value: 117  , label: "Avalon"},
    {value: 118  , label: "Aviation"},
    {value: 119  , label: "Aztec Punch"},
    {value: 120  , label: "B-52"},
    {value: 121  , label: "B-53"},
    {value: 122  , label: "Baby Eskimo"},
    {value: 123  , label: "Baby Guinness"},
    {value: 124  , label: "Bacardi Cocktail"},
    {value: 125  , label: "Bailey's Dream Shake"},
    {value: 126  , label: "Balmoral"},
    {value: 127  , label: "Banana Cantaloupe Smoothie"},
    {value: 128  , label: "Banana Daiquiri"},
    {value: 129  , label: "Banana Milk Shake"},
    {value: 130  , label: "Banana Strawberry Shake"},
    {value: 131  , label: "Banana Strawberry Shake Daiquiri-type"},
    {value: 132  , label: "Barracuda"},
    {value: 133  , label: "Belgian Blue"},
    {value: 134  , label: "Bellini"},
    {value: 135  , label: "Bellini Martini"},
    {value: 136  , label: "Bermuda Highball"},
    {value: 137  , label: "Berry Deadly"},
    {value: 138  , label: "Between The Sheets"},
    {value: 139  , label: "Bible Belt"},
    {value: 140  , label: "Big Red"},
    {value: 141  , label: "Black & Tan"},
    {value: 142  , label: "Black Forest Shake"},
    {value: 143  , label: "Black Russian"},
    {value: 144  , label: "Black and Brown"},
    {value: 145  , label: "Blackthorn"},
    {value: 146  , label: "Bleeding Surgeon"},
    {value: 147  , label: "Blind Russian"},
    {value: 148  , label: "Bloody Maria"},
    {value: 149  , label: "Bloody Mary"},
    {value: 150  , label: "Blue Lagoon"},
    {value: 151  , label: "Blue Margarita"},
    {value: 152  , label: "Blue Mountain"},
    {value: 153  , label: "Bluebird"},
    {value: 154  , label: "Bob Marley"},
    {value: 155  , label: "Bobby Burns Cocktail"},
    {value: 156  , label: "Boomerang"},
    {value: 157  , label: "Boozy Snickers Milkshake"},
    {value: 158  , label: "Bora Bora"},
    {value: 159  , label: "Boston Sidecar"},
    {value: 160  , label: "Boston Sour"},
    {value: 161  , label: "Bourbon Sling"},
    {value: 162  , label: "Bourbon Sour"},
    {value: 163  , label: "Boxcar"},
    {value: 164  , label: "Brain Fart"},
    {value: 165  , label: "Brainteaser"},
    {value: 166  , label: "Bramble"},
    {value: 167  , label: "Brandon and Will's Coke Float"},
    {value: 168  , label: "Brandy Alexander"},
    {value: 169  , label: "Brandy Cobbler"},
    {value: 170  , label: "Brandy Flip"},
    {value: 171  , label: "Brandy Sour"},
    {value: 172  , label: "Brave Bull Shooter"},
    {value: 173  , label: "Bruce's Puce"},
    {value: 174  , label: "Bruised Heart"},
    {value: 175  , label: "Bubble Gum"},
    {value: 176  , label: "Buccaneer"},
    {value: 177  , label: "Bumble Bee #1"},
    {value: 178  , label: "Butter Baby"},
    {value: 179  , label: "Cafe Savoy"},
    {value: 180  , label: "Caipirinha"},
    {value: 181  , label: "Caipirissima"},
    {value: 182  , label: "California Lemonade"},
    {value: 183  , label: "California Root Beer"},
    {value: 184  , label: "Campari Beer"},
    {value: 185  , label: "Caribbean Boilermaker"},
    {value: 186  , label: "Caribbean Orange Liqueur"},
    {value: 187  , label: "Casino"},
    {value: 188  , label: "Casino Royale"},
    {value: 189  , label: "Castillian Hot Chocolate"},
    {value: 190  , label: "Champagne Cocktail"},
    {value: 191  , label: "Cherry Electric Lemonade"},
    {value: 192  , label: "Cherry Rum"},
    {value: 193  , label: "Chicago Fizz"},
    {value: 194  , label: "Chocolate Beverage"},
    {value: 195  , label: "Chocolate Black Russian"},
    {value: 196  , label: "Chocolate Drink"},
    {value: 197  , label: "Chocolate Milk"},
    {value: 198  , label: "Chocolate Monkey"},
    {value: 199  , label: "Citrus Coke"},
    {value: 200  , label: "City Slicker"},
    {value: 201  , label: "Classic Old-Fashioned"},
    {value: 202  , label: "Clove Cocktail"},
    {value: 203  , label: "Clover Club"},
    {value: 204  , label: "Coffee Liqueur"},
    {value: 205  , label: "Coffee-Vodka"},
    {value: 206  , label: "Coke and Drops"},
    {value: 207  , label: "Cosmopolitan"},
    {value: 208  , label: "Cosmopolitan Martini"},
    {value: 209  , label: "Cranberry Cordial"},
    {value: 210  , label: "Cranberry Punch"},
    {value: 211  , label: "Cream Soda"},
    {value: 212  , label: "Creme de Menthe"},
    {value: 213  , label: "Cuba Libra"},
    {value: 214  , label: "Cuba Libre"},
    {value: 215  , label: "Daiquiri"},
    {value: 216  , label: "Damned if you do"},
    {value: 217  , label: "Danbooka"},
    {value: 218  , label: "Dark Caipirinha"},
    {value: 219  , label: "Dark and Stormy"},
    {value: 220  , label: "Darkwood Sling"},
    {value: 221  , label: "Derby"},
    {value: 222  , label: "Diesel"},
    {value: 223  , label: "Dirty Martini"},
    {value: 224  , label: "Dirty Nipple"},
    {value: 225  , label: "Downshift"},
    {value: 226  , label: "Dragonfly"},
    {value: 227  , label: "Drinking Chocolate"},
    {value: 228  , label: "Dry Rob Roy"},
    {value: 229  , label: "Dubonnet Cocktail"},
    {value: 230  , label: "Duchamp's Punch"},
    {value: 231  , label: "Egg Cream"},
    {value: 232  , label: "Egg Nog #4"},
    {value: 233  , label: "Egg Nog - Healthy"},
    {value: 234  , label: "Egg-Nog - Classic Cooked"},
    {value: 235  , label: "English Highball"},
    {value: 236  , label: "English Rose Cocktail"},
    {value: 237  , label: "Espresso Martini"},
    {value: 238  , label: "Fahrenheit 5000"},
    {value: 239  , label: "Flaming Dr. Pepper"},
    {value: 240  , label: "Flaming Lamborghini"},
    {value: 241  , label: "Flander's Flake-Out"},
    {value: 242  , label: "Flying Dutchman"},
    {value: 243  , label: "Flying Scotchman"},
    {value: 244  , label: "Foxy Lady"},
    {value: 245  , label: "Frappé"},
    {value: 246  , label: "Freddy Kruger"},
    {value: 247  , label: "French \"75"},
    {value: 248  , label: "French 75"},
    {value: 249  , label: "French Connection"},
    {value: 250  , label: "French Martini"},
    {value: 251  , label: "Frisco Sour"},
    {value: 252  , label: "Frozen Daiquiri"},
    {value: 253  , label: "Frozen Mint Daiquiri"},
    {value: 254  , label: "Frozen Pineapple Daiquiri"},
    {value: 255  , label: "Fruit Cooler"},
    {value: 256  , label: "Fruit Flip-Flop"},
    {value: 257  , label: "Fruit Shake"},
    {value: 258  , label: "Fuzzy Asshole"},
    {value: 259  , label: "GG"},
    {value: 260  , label: "Gagliardo"},
    {value: 261  , label: "Gentleman's Club"},
    {value: 262  , label: "Gideon's Green Dinosaur"},
    {value: 263  , label: "Gin And Tonic"},
    {value: 264  , label: "Gin Cooler"},
    {value: 265  , label: "Gin Daisy"},
    {value: 266  , label: "Gin Fizz"},
    {value: 267  , label: "Gin Rickey"},
    {value: 268  , label: "Gin Sling"},
    {value: 269  , label: "Gin Smash"},
    {value: 270  , label: "Gin Sour"},
    {value: 271  , label: "Gin Squirt"},
    {value: 272  , label: "Gin Swizzle"},
    {value: 273  , label: "Gin Toddy"},
    {value: 274  , label: "Girl From Ipanema"},
    {value: 275  , label: "Gluehwein"},
    {value: 276  , label: "Godchild"},
    {value: 277  , label: "Godfather"},
    {value: 278  , label: "Godmother"},
    {value: 279  , label: "Golden dream"},
    {value: 280  , label: "Grand Blue"},
    {value: 281  , label: "Grape lemon pineapple Smoothie"},
    {value: 282  , label: "Grass Skirt"},
    {value: 283  , label: "Grasshopper"},
    {value: 284  , label: "Green Goblin"},
    {value: 285  , label: "Grim Reaper"},
    {value: 286  , label: "Grizzly Bear"},
    {value: 287  , label: "H.D."},
    {value: 288  , label: "Happy Skipper"},
    {value: 289  , label: "Harvey Wallbanger"},
    {value: 290  , label: "Havana Cocktail"},
    {value: 291  , label: "Hawaiian Cocktail"},
    {value: 292  , label: "Hemingway Special"},
    {value: 293  , label: "Herbal flame"},
    {value: 294  , label: "Highland Fling Cocktail"},
    {value: 295  , label: "Holloween Punch"},
    {value: 296  , label: "Homemade Kahlua"},
    {value: 297  , label: "Horse's Neck"},
    {value: 298  , label: "Hot Chocolate to Die for"},
    {value: 299  , label: "Hot Creamy Bush"},
    {value: 300  , label: "Ice Pick #1"},
    {value: 301  , label: "Iced Coffee"},
    {value: 302  , label: "Iced Coffee Fillip"},
    {value: 303  , label: "Imperial Cocktail"},
    {value: 304  , label: "Imperial Fizz"},
    {value: 305  , label: "Ipamena"},
    {value: 306  , label: "Irish Coffee"},
    {value: 307  , label: "Irish Cream"},
    {value: 308  , label: "Irish Curdling Cow"},
    {value: 309  , label: "Irish Russian"},
    {value: 310  , label: "Irish Spring"},
    {value: 311  , label: "Jack Rose Cocktail"},
    {value: 312  , label: "Jack's Vanilla Coke"},
    {value: 313  , label: "Jackhammer"},
    {value: 314  , label: "Jam Donut"},
    {value: 315  , label: "Jamaica Kiss"},
    {value: 316  , label: "Jamaican Coffee"},
    {value: 317  , label: "Japanese Fizz"},
    {value: 318  , label: "Jello shots"},
    {value: 319  , label: "Jelly Bean"},
    {value: 320  , label: "Jewel Of The Nile"},
    {value: 321  , label: "Jitterbug"},
    {value: 322  , label: "John Collins"},
    {value: 323  , label: "Just a Moonmint"},
    {value: 324  , label: "Kamikaze"},
    {value: 325  , label: "Karsk"},
    {value: 326  , label: "Kentucky B And B"},
    {value: 327  , label: "Kentucky Colonel"},
    {value: 328  , label: "Kill the cold Smoothie"},
    {value: 329  , label: "Kioki Coffee"},
    {value: 330  , label: "Kir"},
    {value: 331  , label: "Kir Royale"},
    {value: 332  , label: "Kiss me Quick"},
    {value: 333  , label: "Kiwi Lemon"},
    {value: 334  , label: "Kiwi Papaya Smoothie"},
    {value: 335  , label: "Kool First Aid"},
    {value: 336  , label: "Kool-Aid Shot"},
    {value: 337  , label: "Kool-Aid Slammer"},
    {value: 338  , label: "Kurant Tea"},
    {value: 339  , label: "Lady Love Fizz"},
    {value: 340  , label: "Lassi - A South Indian Drink"},
    {value: 341  , label: "Lassi - Mango"},
    {value: 342  , label: "Lassi - Sweet"},
    {value: 343  , label: "Lassi Khara"},
    {value: 344  , label: "Lassi Raita"},
    {value: 345  , label: "Lemon Drop"},
    {value: 346  , label: "Lemon Shot"},
    {value: 347  , label: "Lemouroudji"},
    {value: 348  , label: "Limeade"},
    {value: 349  , label: "Limona Corona"},
    {value: 350  , label: "Loch Lomond"},
    {value: 351  , label: "London Town"},
    {value: 352  , label: "Lone Tree Cocktail"},
    {value: 353  , label: "Lone Tree Cooler"},
    {value: 354  , label: "Long Island Iced Tea"},
    {value: 355  , label: "Long Island Tea"},
    {value: 356  , label: "Long vodka"},
    {value: 357  , label: "Lord And Lady"},
    {value: 358  , label: "Lunch Box"},
    {value: 359  , label: "Mai Tai"},
    {value: 360  , label: "Malibu Twister"},
    {value: 361  , label: "Mango Orange Smoothie"},
    {value: 362  , label: "Manhattan"},
    {value: 363  , label: "Margarita"},
    {value: 364  , label: "Martinez Cocktail"},
    {value: 365  , label: "Martini"},
    {value: 366  , label: "Mary Pickford"},
    {value: 367  , label: "Masala Chai"},
    {value: 368  , label: "Melya"},
    {value: 369  , label: "Miami Vice"},
    {value: 370  , label: "Microwave Hot Cocoa"},
    {value: 371  , label: "Midnight Cowboy"},
    {value: 372  , label: "Midnight Manx"},
    {value: 373  , label: "Midnight Mint"},
    {value: 374  , label: "Mimosa"},
    {value: 375  , label: "Mississippi Planters Punch"},
    {value: 376  , label: "Mocha-Berry"},
    {value: 377  , label: "Mojito"},
    {value: 378  , label: "Mojito #3"},
    {value: 379  , label: "Monkey Gland"},
    {value: 380  , label: "Monkey Wrench"},
    {value: 381  , label: "Moranguito"},
    {value: 382  , label: "Moscow Mule"},
    {value: 383  , label: "Mother's Milk"},
    {value: 384  , label: "Mudslinger"},
    {value: 385  , label: "Mulled Wine"},
    {value: 386  , label: "National Aquarium"},
    {value: 387  , label: "Negroni"},
    {value: 388  , label: "New York Lemonade"},
    {value: 389  , label: "New York Sour"},
    {value: 390  , label: "Nuked Hot Chocolate"},
    {value: 391  , label: "Nutty Irishman"},
    {value: 392  , label: "Old Fashioned"},
    {value: 393  , label: "Orange Crush"},
    {value: 394  , label: "Orange Oasis"},
    {value: 395  , label: "Orange Push-up"},
    {value: 396  , label: "Orange Scented Hot Chocolate"},
    {value: 397  , label: "Orange Whip"},
    {value: 398  , label: "Orangeade"},
    {value: 399  , label: "Oreo Mudslide"},
    {value: 400  , label: "Orgasm"},
    {value: 401  , label: "Owen's Grandmother's Revenge"},
    {value: 402  , label: "Paradise"},
    {value: 403  , label: "Pina Colada"},
    {value: 404  , label: "Pineapple Gingerale Smoothie"},
    {value: 405  , label: "Pink Gin"},
    {value: 406  , label: "Pink Lady"},
    {value: 407  , label: "Pink Panty Pulldowns"},
    {value: 408  , label: "Pink Penocha"},
    {value: 409  , label: "Pisco Sour"},
    {value: 410  , label: "Planter's Punch"},
    {value: 411  , label: "Popped cherry"},
    {value: 412  , label: "Poppy Cocktail"},
    {value: 413  , label: "Port And Starboard"},
    {value: 414  , label: "Port Wine Cocktail"},
    {value: 415  , label: "Port Wine Flip"},
    {value: 416  , label: "Porto flip"},
    {value: 417  , label: "Pysch Vitamin Light"},
    {value: 418  , label: "Quaker's Cocktail"},
    {value: 419  , label: "Quarter Deck Cocktail"},
    {value: 420  , label: "Queen Bee"},
    {value: 421  , label: "Queen Charlotte"},
    {value: 422  , label: "Queen Elizabeth"},
    {value: 423  , label: "Quentin"},
    {value: 424  , label: "Quick F**K"},
    {value: 425  , label: "Quick-sand"},
    {value: 426  , label: "Radioactive Long Island Iced Tea"},
    {value: 427  , label: "Radler"},
    {value: 428  , label: "Rail Splitter"},
    {value: 429  , label: "Raspberry Cooler"},
    {value: 430  , label: "Red Snapper"},
    {value: 431  , label: "Rose"},
    {value: 432  , label: "Royal Bitch"},
    {value: 433  , label: "Royal Fizz"},
    {value: 434  , label: "Royal Flush"},
    {value: 435  , label: "Royal Gin Fizz"},
    {value: 436  , label: "Ruby Tuesday"},
    {value: 437  , label: "Rum Cobbler"},
    {value: 438  , label: "Rum Cooler"},
    {value: 439  , label: "Rum Milk Punch"},
    {value: 440  , label: "Rum Old-fashioned"},
    {value: 441  , label: "Rum Punch"},
    {value: 442  , label: "Rum Runner"},
    {value: 443  , label: "Rum Screwdriver"},
    {value: 444  , label: "Rum Sour"},
    {value: 445  , label: "Rum Toddy"},
    {value: 446  , label: "Russian Spring Punch"},
    {value: 447  , label: "Rusty Nail"},
    {value: 448  , label: "Salty Dog"},
    {value: 449  , label: "San Francisco"},
    {value: 450  , label: "Sangria #1"},
    {value: 451  , label: "Sangria - The World's Best"},
    {value: 452  , label: "Sazerac"},
    {value: 453  , label: "Scooter"},
    {value: 454  , label: "Scotch Cobbler"},
    {value: 455  , label: "Scotch Sour"},
    {value: 456  , label: "Scottish Highland Liqueur"},
    {value: 457  , label: "Screaming Orgasm"},
    {value: 458  , label: "Screwdriver"},
    {value: 459  , label: "Sea breeze"},
    {value: 460  , label: "Sex on the Beach"},
    {value: 461  , label: "Shanghai Cocktail"},
    {value: 462  , label: "Shark Attack"},
    {value: 463  , label: "Sherry Eggnog"},
    {value: 464  , label: "Sherry Flip"},
    {value: 465  , label: "Shot-gun"},
    {value: 466  , label: "Sidecar"},
    {value: 467  , label: "Sidecar Cocktail"},
    {value: 468  , label: "Singapore Sling"},
    {value: 469  , label: "Sloe Gin Cocktail"},
    {value: 470  , label: "Smut"},
    {value: 471  , label: "Snake Bite (UK)"},
    {value: 472  , label: "Snakebite and Black"},
    {value: 473  , label: "Snowball"},
    {value: 474  , label: "Sol Y Sombra"},
    {value: 475  , label: "Space Odyssey"},
    {value: 476  , label: "Spanish chocolate"},
    {value: 477  , label: "Spiced Peach Punch"},
    {value: 478  , label: "Spiking coffee"},
    {value: 479  , label: "Spritz"},
    {value: 480  , label: "Stinger"},
    {value: 481  , label: "Stone Sour"},
    {value: 482  , label: "Strawberry Daiquiri"},
    {value: 483  , label: "Strawberry Lemonade"},
    {value: 484  , label: "Strawberry Margarita"},
    {value: 485  , label: "Strawberry Shivers"},
    {value: 486  , label: "Sunny Holiday Punch"},
    {value: 487  , label: "Surf City Lifesaver"},
    {value: 488  , label: "Swedish Coffee"},
    {value: 489  , label: "Sweet Bananas"},
    {value: 490  , label: "Sweet Sangria"},
    {value: 491  , label: "Sweet Tooth"},
    {value: 492  , label: "Talos Coffee"},
    {value: 493  , label: "Tennesee Mud"},
    {value: 494  , label: "Tequila Fizz"},
    {value: 495  , label: "Tequila Sour"},
    {value: 496  , label: "Tequila Sunrise"},
    {value: 497  , label: "Tequila Surprise"},
    {value: 498  , label: "Texas Rattlesnake"},
    {value: 499  , label: "Texas Sling"},
    {value: 500  , label: "Thai Coffee"},
    {value: 501  , label: "Thai Iced Coffee"},
    {value: 502  , label: "Thai Iced Tea"},
    {value: 503  , label: "The Evil Blue Thing"},
    {value: 504  , label: "Thriller"},
    {value: 505  , label: "Tia-Maria"},
    {value: 506  , label: "Tom Collins"},
    {value: 507  , label: "Tomato Tang"},
    {value: 508  , label: "Tommy's Margarita"},
    {value: 509  , label: "Turf Cocktail"},
    {value: 510  , label: "Turkeyball"},
    {value: 511  , label: "Tuxedo Cocktail"},
    {value: 512  , label: "Valencia Cocktail"},
    {value: 513  , label: "Vampiro"},
    {value: 514  , label: "Van Vleet"},
    {value: 515  , label: "Vermouth Cassis"},
    {value: 516  , label: "Vesper"},
    {value: 517  , label: "Vesuvio"},
    {value: 518  , label: "Veteran"},
    {value: 519  , label: "Victor"},
    {value: 520  , label: "Victory Collins"},
    {value: 521  , label: "Vodka And Tonic"},
    {value: 522  , label: "Vodka Fizz"},
    {value: 523  , label: "Vodka Martini"},
    {value: 524  , label: "Vodka Russian"},
    {value: 525  , label: "Waikiki Beachcomber"},
    {value: 526  , label: "Whiskey Sour"},
    {value: 527  , label: "Whisky Mac"},
    {value: 528  , label: "White Lady"},
    {value: 529  , label: "White Russian"},
    {value: 530  , label: "Whitecap Margarita"},
    {value: 531  , label: "Wine Cooler"},
    {value: 532  , label: "Wine Punch"},
    {value: 533  , label: "Yellow Bird"},
    {value: 534  , label: "Yoghurt Cooler"},
    {value: 535  , label: "Zambeer"},
    {value: 536  , label: "Zenmeister"},
    {value: 537  , label: "Ziemes Martini Apfelsaft"},
    {value: 538  , label: "Zima Blaster"},
    {value: 539  , label: "Zimadori Zinger"},
    {value: 540  , label: "Zinger"},
    {value: 541  , label: "Zipperhead"},
    {value: 542  , label: "Zippy's Revenge"},
    {value: 543  , label: "Zizi Coin-coin"},
    {value: 544  , label: "Zoksel"},
    {value: 545  , label: "Zorbatini"},
    {value: 546  , label: "Zorro"},
	]